apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env
  namespace: snacktime-recipes
data:
  HOST: "0.0.0.0"
  PORT: "3000"
  NODE_ENV: "production"
  APP_KEY: "9UaTGJZqlVe6AFawap6p87TKEx-8XuxN"
  DRIVE_DISK: "local"
  DB_CONNECTION: "sqlite"
  SESSION_DRIVER: "cookie"
