apiVersion: v1
kind: Secret
metadata:
  name: social-keys
  namespace: snacktime-recipes
type: Opaque
data:
  GOOGLE_CLIENT_ID: clientId
  GOOGLE_CLIENT_SECRET: clientSecret

  DISCORD_CLIENT_ID: clientId
  DISCORD_CLIENT_SECRET: clientSecret

  TWITTER_CLIENT_ID: clientId
  TWITTER_CLIENT_SECRET: clientSecret
  
  FACEBOOK_CLIENT_ID: clientId
  FACEBOOK_CLIENT_SECRET: clientSecret
