apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env
data:
  HOST: "0.0.0.0"
  PORT: "3000"
  NODE_ENV: "production"
  APP_KEY: "9UaTGJZqlVe6AFawap6p87TKEx-8XuxN"
  DRIVE_DISK: "local"
  SESSION_DRIVER: "cookie"
  COOKIE_DOMAIN: "dev.snacktime.recipes"
  SEARCH_API_KEY: setInProduction
  APP_URL: "https://dev.snacktime.recipes"

  DB_CONNECTION: "sqlite"