apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: snacktime-recipes
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: registry.odzi.dog/snacktime-recipes/backend:latest
        envFrom:
          - configMapRef:
              name: backend-env
        volumeMounts:
          - mountPath: "/code/tmp"
            name: database
        ports:
        - containerPort: 3000
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: sqlite-database

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: snacktime-recipes
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    name: entrypoint
    targetPort: 3000

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backend
  namespace: snacktime-recipes
spec:
  entryPoints:
  - web
  - websecure
  routes:
    - match: Host(`api.dev.snacktime.recipes`)
      kind: Rule
      services:
        - name: backend
          port: entrypoint
  tls:
    certResolver: "cloudflare"