apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: snacktime-recipes
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registry.odzi.dog/snacktime-recipes/web:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: snacktime-recipes
spec:
  selector:
    app: frontend
  ports:
  - name: entrypoint
    port: 3000
    targetPort: 3000

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend
  namespace: snacktime-recipes
spec:
  entryPoints:
  - web
  - websecure
  routes:
    - match: Host(`dev.snacktime.recipes`)
      kind: Rule
      services:
        - name: frontend
          port: entrypoint
  tls:
    certResolver: "cloudflare"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-root
  namespace: snacktime-recipes
spec:
  entryPoints:
  - web
  - websecure
  routes:
    - match: Host(`snacktime.recipes`)
      kind: Rule
      services:
        - name: frontend
          port: entrypoint
      middlewares:
        - name: redirect-to-dev
  tls:
    certResolver: "cloudflare"

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-dev
  namespace: snacktime-recipes
spec:
  redirectRegex:
    regex: ^https://snacktime.recipes/(.*)
    replacement: https://dev.snacktime.recipes/${1}